version: '3.5'

services:

  nginx:
    image: ${COMPOSE_PROJECT_NAME}-nginx:latest
    build:
      context: ./.docker/
      args:
        BUILD_ARGUMENT_ENV: dev
      dockerfile: ./nginx/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    ports:
      - "${WEB_PORT_HTTP}:80"
      - "${WEB_PORT_SSL}:443"
    volumes:
      - .:/var/www/html:ro,cached
    depends_on:
      - symfony
    networks:
      - symfony

  mongodb:
    #        image: 077428399685.dkr.ecr.us-east-1.amazonaws.com/local-hireme-mongodb:v4.2.0
    image: mongo:6.0
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb
    hostname: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - symfony

  symfony:
    &symfony-template
    image: ${COMPOSE_PROJECT_NAME}-symfony:latest
    build:
      context: .
      args:
        BUILD_ARGUMENT_ENV: dev
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
        XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-symfony
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - mongodb
#      - rabbitmq
#      - rabbitmq
    networks:
      - symfony

#  ### Cron tasks, RabbitMQ consumers
#  supervisord:
#    <<: *symfony-template
#    container_name: ${COMPOSE_PROJECT_NAME}-supervisord
#    expose: []
#    command: [ "/usr/bin/supervisord" ]
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:5.0.2
#    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
#    environment:
#      # MYSQL_ROOT_PASSWORD: root
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      # PMA_USER: ${DATABASE_USER:-user}
#      # PMA_PASSWORD: ${DATABASE_PASSWORD:-pass}
#      PMA_ARBITRARY: 1
#    restart: always
#    depends_on:
#      - mysql
#    ports:
#      - '8081:80'
#    networks:
#      - symfony
#
#  mysql:
#    image: mysql:8.0
#    platform: linux/x86_64
#    container_name: ${COMPOSE_PROJECT_NAME}-mysql
#    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1}
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: ${DATABASE_DB:-msg}
#      MYSQL_USER: ${DATABASE_USER:-user}
#      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-pass}
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./.docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#    networks:
#      - symfony
#
#  rabbitmq:
#    image: ${COMPOSE_PROJECT_NAME}-rabbitmq
#    build:
#      context: ./.docker/rabbitmq/
#      dockerfile: ./Dockerfile
#    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
#    environment:
#      RABBITMQ_ERLANG_COOKIE: 7ead507151fc4461b9f45c1161384a04
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#      RABBITMQ_DEFAULT_VHOST: /
#    ports:
#      - "15672:15672"
#    volumes:
#      - ./var/rabbitmq:/var/lib/rabbitmq:delegated
#    networks:
#      - symfony

networks:
  symfony:
    name: symfony

volumes:
  mysql_data: ~
  mongodb_data: ~
