#imports:
#  - { resource: parameters.yml }
services:

    CQRS\Product\Domain\Repository\ProductRepositoryInterface:
      # the first argument is the class and the second argument is the static method
      factory: [ '@CQRS\Product\Infrastructure\External\ServiceFactory\ProductRepositoryFactory', 'create' ]
