imports:
  - { resource: parameters.yml }
services:
  CQRS\Common\Infrastructure\External\Database\MongodbClient:
    factory: [null, 'create']
    arguments:
      $mongodbUrl: '%MONGODB_URL%'
      $mongodbDb: '%MONGODB_DB%'