name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.0]

    services:
      mongodb:
        build:
          context: .
          dockerfile: docker-compose-test.yml
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'printjson(db.serverStatus())'" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Start MongoDB container
        run: docker-compose up -d

      - name: Wait for MongoDB
        run: docker-compose -f docker-compose-test.yml exec mongodb bash -c 'while ! mongo --eval "printjson(db.serverStatus())"; do sleep 1; done'

#      - name: Install MongoDB PHP library
#        run: composer require mongodb/mongodb
#
#      - name: Install dependencies
#        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017/cqrs_test
        run: php bin/phpunit