name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.0]

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'printjson(db.serverStatus())'" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install MongoDB extension
        run: sudo pecl install mongodb

      - name: Enable MongoDB extension
        run: echo "extension=mongodb.so" >> ${{ phpini }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017
        run: composer test