name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

env:
  ENV_FILE: .env.test
  APP_ENV: test
  MONGODB_URL: mongodb://admin:root@localhost:27017/cqrs_test?authSource=admin
  MONGODB_DB: cqrs_test
  BACKUP_PATH: data/backup
  BACKUP_FILE_NAME: mongodb.tar.gz

jobs:
  symfony:
    name: Symfony cqrs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2]

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mongodb

      - name: Copy .env.test
        run: cp ${{ env.ENV_FILE }} .env

      - name: Debug Environment Variables
        run: printenv

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --prefer-dist

      - name: Generate and load fixtures
        run: |
          php bin/console m:f:l --env=test --no-interaction

      - name: Backup database
        run: |
          mkdir -p data/backup
          CONTAINER_ID=$(docker ps -qf "name=${{ job.services.mongodb.name }}")
          docker exec "${CONTAINER_ID}" mongodump --uri "${{ env.MONGODB_URL }}" --authenticationDatabase=admin --gzip --archive=/data/db/backup/mongodb_dump.archive  --username admin --password root
          docker cp "${CONTAINER_ID}:/data/db/backup/mongodb_dump.archive" "${{ github.workspace }}/${{ env.BACKUP_PATH }}/${{ env.BACKUP_FILE_NAME }}.archive"

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v2
        with:
          name: database-backup
          path: ${{ github.workspace }}/${{ env.BACKUP_PATH }}/${{ env.BACKUP_FILE_NAME }}

      - name: Download backup artifact
        uses: actions/download-artifact@v2
        with:
          name: database-backup
          path: ${{ env.BACKUP_PATH }}

      - name: Run tests
        run: php vendor/bin/phpunit --configuration phpunit.xml.dist
